apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deploy
  labels:
    app: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      name: php-deploy
      labels:
        app: webserver
    spec:
      volumes:
        - name: php-pv-vol
          persistentVolumeClaim:
            claimName: php-pv-vol-claim
        
      containers:
        - name: php-deploy
          image: rajnishthegreat/php:v1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: "/var/log/httpd"
              name: php-pv-vol